proiectdj/aplicatie3/urls.py
from django.urls import path

from aplicatie3 import views

app_name = 'aplicatie3'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_jobs/', views.CreateJobsView.as_view(), name="adaugare"),
    path('edit_jobs/<int:pk>/', views.UpdateJobsView.as_view(), name="modificare"),
]

proiectdj/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('aplicatie3.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
]

proiectdj/aplicatie3/models.py
from django.db import models

# Create your models here.
from aplicatie2.models import Companies

job_choices = (('Full-time', 'Full-time'),
               ('Part-time', 'Part-time'),
               ('Project-based', 'Project-based'),
               ('Volunteering', 'Volunteering'))


class Jobs(models.Model):

    type = models.CharField(max_length=50, choices=job_choices)
    url = models.CharField(max_length=100)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    how_to_apply = models.CharField(max_length=500)
    company = models.ForeignKey(Companies, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} from {self.companies.name} name  - {self.companies.location} location"

proiectdj/aplicatie3/forms.py
from django import forms
from django.forms import TextInput, Select

from aplicatie3.models import Jobs


class JobsForm(forms.ModelForm):
    class Meta:
        model = Jobs
        fields = ['type', 'url', 'title', 'description', 'how_to_apply', 'company']

        widgets = {
            'type': Select(attrs={'class': 'form-control'}),
            'url': TextInput(attrs={'placeholder': 'URL', 'class': 'form-control'}),
            'title': TextInput(attrs={'placeholder': 'Job title', 'class': 'form-control'}),
            'description': TextInput(attrs={'placeholder': 'Job description', 'class': 'form-control'}),
            'how_to_apply': TextInput(attrs={'placeholder': 'How to apply', 'class': 'form-control'}),
            'company': Select(attrs={'class': 'form-control'})
        }

proiectdj/aplicatie3/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
# ListView => Afisare date
# CreateView => Adaugare date
# UpdateView => Modificare date
# DeleteView => Stergere date
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie3.forms import JobsForm
from aplicatie3.models import Jobs


class HomeIndex(LoginRequiredMixin, ListView):
    model = Jobs
    template_name = 'aplicatie3/jobs_index.html'
    context_object_name = 'all_jobs'


class CreateJobsView(LoginRequiredMixin, CreateView):
    model = Jobs
    # fields = ['type', 'url', 'title', 'description', 'how_to_apply', 'company']
    form_class = JobsForm
    template_name = 'aplicatie1/location_form.html'

    def get_success_url(self):
        return reverse('aplicatie3:home')


class UpdateJobsView(LoginRequiredMixin, UpdateView):
    model = Jobs
    # fields = ['name', 'website', 'type', 'active', 'location']
    form_class = JobsForm
    template_name = 'aplicatie1/location_form.html'

    def get_success_url(self):
        return reverse('aplicatie3:modificare', kwargs={'pk': self.kwargs['pk']})

proiectdj/templates/aplicatie3/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <a href="{% url 'aplicatie3:adaugare' %}" class="header_style">Adaugare</a>
    <table id="id_tabel">
        <thead class="header_style">
        <th>Counter</th>
        <th>Type</th>
        <th>URL</th>
        <th>Title</th>
        <th>Description</th>
        <th>HowToApply</th>
        <th>Company</th>
        <th>Actions</th>
        </thead>
        <tbody>
        {% for item in all_jobs %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.type }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.how_to_apply }}</td>
                <td>{{ item.company.name }}</td>
                <td><a href="{% url 'aplicatie3:modificare' item.id %}">Edit</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}