proiectdj/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'aplicatie1'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_location/', views.CreateIndexView.as_view(), name="adaugare"),
    path('edit_location/<int:pk>/', views.UpdateLocationView.as_view(), name="modificare"),
]

proiectdj/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('aplicatie3.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
]

proiectdj/aplicatie1/models.py
from django.db import models

# Create your models here.


class Location(models.Model):

    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.city} - {self.country}"

proiectdj/aplicatie1/forms.py
from django import forms
from django.forms import TextInput

from aplicatie1.models import Location


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['city', 'country']

        widgets = {
            'city': TextInput(attrs={'placeholder': 'City name', 'class': 'form-control'}),
            'country': TextInput(attrs={'placeholder': 'Country name', 'class': 'form-control'}),
        }

    def __init__(self, pk, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        self.pk = pk

    def clean(self):
        cleaned_data = self.cleaned_data
        city_val = cleaned_data.get('city')
        country_val = cleaned_data.get('country')
        if self.pk:
            if Location.objects.filter(city=city_val, country=country_val).exclude(id=self.pk).exists():
                msg = 'City and country already exist'
                self._errors['city'] = self.error_class([msg])
        else:
            if Location.objects.filter(city=city_val, country=country_val).exists():
                msg = 'City and country already exist'
                self._errors['city'] = self.error_class([msg])
        return cleaned_data

proiectdj/aplicatie1/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
# ListView => Afisare date
# CreateView => Adaugare date
# UpdateView => Modificare date
# DeleteView => Stergere date
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie1.forms import LocationForm
from aplicatie1.models import Location
from django.urls import reverse


class HomeIndex(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie1/location_index.html'
    context_object_name = 'all_locations'


class CreateIndexView(LoginRequiredMixin, CreateView):
    model = Location
    # fields = ['city', 'country']
    form_class = LocationForm
    template_name = 'aplicatie1/location_form.html'

    def get_form_kwargs(self):
        kwargs = super(CreateIndexView, self).get_form_kwargs()
        kwargs.update({'pk': None})
        return kwargs

    def get_success_url(self):
        return reverse('aplicatie1:home')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    # fields = ['city', 'country']
    form_class = LocationForm
    template_name = 'aplicatie1/location_form.html'

    def get_form_kwargs(self):
        kwargs = super(UpdateLocationView, self).get_form_kwargs()
        kwargs.update({'pk': self.kwargs['pk']})
        return kwargs

    def get_success_url(self):
        return reverse('aplicatie1:home')

proiectdj/templates/aplicatie1/location_form.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }}
            {{ field }}
            {{ field.errors }}
        {% endfor %}
        <button type="submit" class="btn btn-success">Salveaza</button>
    </form>
{% endblock %}

proiectdj/templates/aplicatie1/location_index.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <a href="{% url 'aplicatie1:adaugare' %}" class="header_style">Adaugare</a>
    <table id="id_tabel">
        <thead class="header_style">
        <th>Index</th>
        <th>City</th>
        <th>Country</th>
        <th>Actions</th>
        </thead>
        <tbody>
        {% for item in all_locations %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country|upper }}</td>
                <td><a href="{% url 'aplicatie1:modificare' item.id %}">Edit</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}