proiectdj/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'aplicatie2'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_companies/', views.CreateCompaniesView.as_view(), name="adaugare"),
    path('edit_companies/<int:pk>/', views.UpdateCompaniesView.as_view(), name="modificare"),
]

proiectdj/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('aplicatie3.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
]

proiectdj/aplicatie2/models.py
from django.db import models

# Create your models here.
from aplicatie1.models import Location

companies_choices = (('S.R.L.', 'S.R.L.'), ('S.A.', 'S.A.'))


class Companies(models.Model):

    name = models.CharField(max_length=50)
    website = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=companies_choices)
    active = models.BooleanField(default=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} from {self.location.city} city  - {self.location.country} country"

proiectdj/aplicatie2/forms.py
from django import forms
from django.forms import TextInput, Select

from aplicatie2.models import Companies


class CompaniesForm(forms.ModelForm):
    class Meta:
        model = Companies
        fields = ['name', 'website', 'type', 'active', 'location']

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Name of company', 'class': 'form-control'}),
            'website': TextInput(attrs={'placeholder': 'Website', 'class': 'form-control'}),
            'type': Select(attrs={'class': 'form-control'}),
            'location': Select(attrs={'class': 'form-control'})
        }

proiectdj/aplicatie2/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
# ListView => Afisare date
# CreateView => Adaugare date
# UpdateView => Modificare date
# DeleteView => Stergere date
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie2.forms import CompaniesForm
from aplicatie2.models import Companies


class HomeIndex(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'aplicatie2/companies_index.html'
    context_object_name = 'all_companies'


class CreateCompaniesView(LoginRequiredMixin, CreateView):
    model = Companies
    # fields = ['name', 'website', 'type', 'active', 'location']
    form_class = CompaniesForm
    template_name = 'aplicatie1/location_form.html'

    def get_success_url(self):
        return reverse('aplicatie2:home')


class UpdateCompaniesView(LoginRequiredMixin, UpdateView):
    model = Companies
    # fields = ['name', 'website', 'type', 'active', 'location']
    form_class = CompaniesForm
    template_name = 'aplicatie1/location_form.html'

    def get_success_url(self):
        return reverse('aplicatie2:modificare', kwargs={'pk': self.kwargs['pk']})

proiectdj/templates/aplicatie2/companies_index.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <a href="{% url 'aplicatie2:adaugare' %}" class="header_style">Adaugare</a>
    <table id="id_tabel">
        <thead class="header_style">
        <th>Counter</th>
        <th>Name</th>
        <th>Website</th>
        <th>Type</th>
        <th>Active</th>
        <th>Location</th>
        <th>Actions</th>
        </thead>
        <tbody>
        {% for item in all_companies %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.website|upper }}</td>
                <td>{{ item.type }}</td>
                <td>{{ item.active }}</td>
                <td>{{ item.location.city }} {{ item.location.country }}</td>
                <td><a href="{% url 'aplicatie2:modificare' item.id %}">Edit</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}