proiectdj/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'aplicatie1'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_location/', views.CreateIndexView.as_view(), name="adaugare"),
    path('edit_location/<int:pk>/', views.UpdateLocationView.as_view(), name="modificare"),
]

proiectdj/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'aplicatie2'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_companies/', views.CreateCompaniesView.as_view(), name="adaugare"),
    path('edit_companies/<int:pk>/', views.UpdateCompaniesView.as_view(), name="modificare"),
]

proiectdj/aplicatie3/urls.py
from django.urls import path

from aplicatie3 import views

app_name = 'aplicatie3'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_jobs/', views.CreateJobsView.as_view(), name="adaugare"),
    path('edit_jobs/<int:pk>/', views.UpdateJobsView.as_view(), name="modificare"),
]

proiectdj/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('aplicatie3.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
]

proiectdj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body class="about-us">
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent nav-down" color-on-scroll="200">
    <div class="container">
        <div class="navbar-translate">
            <div class="navbar-header">

            </div>
            <button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse"
                    data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'aplicatie1:home' %}" class="nav-link" style="color:black">
                        Location
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'aplicatie3:home' %}" class="nav-link" style="color:black">
                        Jobs
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'aplicatie2:home' %}" class="nav-link" style="color:black">
                        Companies
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a>{{ request.user.username }}</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated == False %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">
                            Login
                        </a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated == True %}
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="nav-link">
                            Logout
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="page-header page-header-small">
    <div class="filter filter-danger"></div>
    <div class="content-center">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>